name: roslyn
description: |
  The Roslyn .NET compiler provides C# and Visual Basic languages with rich code analysis APIs.
homepage: https://github.com/dotnet/roslyn
licenses:
  - MIT
languages:
  - C#
categories:
  - LSP

source:
  id: pkg:nuget/roslyn-language-server@5.5.0-2.26103.6

bin:
  roslyn-language-server: nuget:roslyn-language-server
